server:
  port: 8083

spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-APP
         predicates:
           - Path=/swiggy/**


       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**
           
     discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
           
        
 application:
    name: SWIGGY-GATEWAY
